### ISSUE TITLE
Consider using optimized Chevrotain Token types to increase performance

### ISSUE THREAD

**Issue by bd82** [kdex/chi#3]
https://github.com/SAP/chevrotain/blob/master/docs/token_types.md

See benchmark:
http://sap.github.io/chevrotain/performance/token_types/

**Comment by kdex** [comment]
Thanks! I think I already tried to switch to `LazyToken` a few days ago by changing this line in `src/Lexer.js`:

```js
import chevrotain, { createToken, Lexer, Token } from "chevrotain";
```

to:

```js
import chevrotain, { createToken, Lexer, LazyToken as Token } from "chevrotain";
```

Unfortunately, that made it break like so:

```js
/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:99
        throw Error("Terminal Token name: " + terminalName + " not found");
        ^

Error: Terminal Token name: Semicolon not found
    at buildTerminalProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:99:15)
    at buildProdGast (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:76:20)
    at /srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:149:25
    at Object.forEach (/srv/http/lang/node_modules/chevrotain/lib/src/utils/utils.js:72:30)
    at buildAbstractProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:148:13)
    at buildProdWithOccurrence (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:111:12)
    at buildOptionProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:139:12)
    at buildProdGast (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:68:20)
    at /srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:149:25
    at Object.forEach (/srv/http/lang/node_modules/chevrotain/lib/src/utils/utils.js:72:30)
```

(I checked whether Semicolon is exported: And yes, it most definitely is.)
So I kept using `Token` until I would know how to resolve this problem.

**Comment by bd82** [comment]
It is because of https://github.com/kdex/chi/blob/master/src/Parser.js#L68
It would still use Token instead of LazyToken so **allTokens** (in parser.js) would be an empty array.
This Chevrotain will be using an empty Token Dictionary.

```JavaScript
const allTokens = Object.values(lexerImports).filter(x => Token.isPrototypeOf(x));
```

You should probably reuse **allTokens** from lexer.js
https://github.com/kdex/chi/blob/master/src/Lexer.js#L164

And perhaps even create it **dynamically** by iterating over the module's own exports:
https://github.com/SAP/chevrotain/blob/master/examples/language_services/src/examples/json/lexer.ts#L23

**Comment by kdex** [comment]
Oh, right! Thanks for spottting this! 👍 

I just tried to fix it by reusing `allTokens` from `Lexer.js`, but then I was hit with:

```js
Error: Terminal Token name: AdditiveOperator not found
    at buildTerminalProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:99:15)
    at buildProdGast (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:76:20)
    at /srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:149:25
    at Object.forEach (/srv/http/lang/node_modules/chevrotain/lib/src/utils/utils.js:72:30)
    at buildAbstractProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:148:13)
    at buildProdWithOccurrence (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:111:12)
    at buildManyProd (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:120:12)
    at buildProdGast (/srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:66:20)
    at /srv/http/lang/node_modules/chevrotain/lib/src/parse/gast_builder.js:149:25
    at Object.forEach (/srv/http/lang/node_modules/chevrotain/lib/src/utils/utils.js:72:30)
```

I then noticed that `AdditiveOperator` and `MultiplicativeOperator` aren't part of `allTokens`, as I intended them to be abstract superclasses. So, after adding them, I'm being hit with:

```js
/srv/http/lang/node_modules/chevrotain/lib/src/scan/lexer_public.js:183
            throw new Error("Errors detected in definition of Lexer:\n" + allErrMessagesString);
            ^

Error: Errors detected in definition of Lexer:
Token class: ->AdditiveOperator<- missing static 'PATTERN' property-----------------------
Token class: ->MultiplicativeOperator<- missing static 'PATTERN' property
    at new Lexer (/srv/http/lang/node_modules/chevrotain/lib/src/scan/lexer_public.js:183:19)
    at new <anonymous> (/srv/http/lang/src/Lexer.js:209:18)
    at Object.<anonymous> (/srv/http/lang/src/index.js:9:15)
    at Module._compile (module.js:571:32)
    at loader (/home/kdex/.npm-global/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/kdex/.npm-global/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
```

… although [they have such a property](https://github.com/kdex/chi/blob/master/src/Lexer.js#L37-L42).

**Comment by bd82** [comment]
See the linked issue above, I will try to make this easier to use.
For now I suggest you filter out any Tokens with PATTERN = NA
From the list given to the Lexer in its initialization.

**Comment by kdex** [comment]
This doesn't behave consistently. I tried to filter the tokens like so:

```js
allTokens.filter(t => t.PATTERN !== NA)
```

and I even inspected this value via `console.log`: It doesn't contain any abstract tokens anymore. It still errors with the same error message as shown above.

If however, I change it like so:

```js
allTokens.filter(t => t != AdditiveOperator && t !== MultiplicativeOperator)
```

it works. That's weird.

Also, it only gave me an error for `AdditiveOperator` and `MultiplicativeOperator` although there's some **more** which it completely ignored, for example [these two]( https://github.com/kdex/chi/blob/master/src/Lexer.js#L88-L93), which are both part of `allTokens`.

**Comment by kdex** [comment]
Oh, wow. Scratch all of that. I don't even have to filter; [I was just too stupid to spell `PATTERN` right](https://github.com/kdex/chi/blob/e9bde49964f7c148c3cf7d984ee4199025f4f1f1/src/Lexer.js#L34-L42). Sorry for the noise!

**Comment by kdex** [comment]
I *really* wonder how this hasn't thrown an error before… 🤣

**Comment by bd82** [comment]
Because it was **never** passed to the Lexer in allTokens
So there was no validation performed. 

And don't worry I'm a pro at typos myself 😄
